# 1. Εγκατάσταση Εργαλείων
[phases.setup]
# ΑΦΑΙΡΕΣΑ το "npm" από εδώ, γιατί περιέχεται στο "nodejs"
nixPkgs = ["python3", "nodejs", "gcc"]

# 2. Εγκατάσταση & Build (Backend + Frontend)
[phases.build]
cmds = [
    # Εγκατάσταση Python πακέτων
    "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt",
    
    # Build του React Frontend
    # Το npm θα δουλέψει κανονικά επειδή βάλαμε το nodejs πάνω
    "cd frontend && npm install && npm run build"
]

# 3. Εκκίνηση Εφαρμογής
[phases.start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"