# 1. Εγκατάσταση Γλωσσών
[phases.setup]
nixPkgs = ["python3", "nodejs", "gcc"]

# 2. Εγκατάσταση Βιβλιοθηκών (Python & Node)
[phases.install]
cmds = [
    # Δεν φτιάχνουμε venv, απλά κάνουμε install
    "pip install -r requirements.txt",
    "cd frontend && npm install"
]

# 3. Build του React
[phases.build]
cmds = [
    "cd frontend && npm run build"
]

# 4. Εκκίνηση
[phases.start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"