# 1. Εγκατάσταση Εργαλείων
[phases.setup]
nixPkgs = ["python311", "nodejs", "gcc"]

# 2. Εγκατάσταση Βιβλιοθηκών
[phases.install]
cmds = [
    # Καλούμε το pip μέσω της python3 και σπάμε τους κανόνες ασφαλείας συστήματος (στο Docker επιτρέπεται)
    "python3 -m pip install -r requirements.txt --break-system-packages",
    "cd frontend && npm install"
]

# 3. Build του React
[phases.build]
cmds = [
    "cd frontend && npm run build"
]

# 4. Εκκίνηση
[phases.start]
cmd = "python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000"